sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t angular-cli-firebase-tools --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg VERSION=`cat VERSION` .
      - docker images
      - docker tag angular-cli-firebase-tools jessieai/angular-cli-firebase-tools
      - docker push jessieai/angular-cli-firebase-tools
